"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

class arm_angles(object):

    __slots__ = ["base", "shoulder", "elbow"]

    __typenames__ = ["float", "float", "float"]

    __dimensions__ = [None, None, None]

    def __init__(self):
        self.base = 0.0
        """ LCM Type: float """
        self.shoulder = 0.0
        """ LCM Type: float """
        self.elbow = 0.0
        """ LCM Type: float """

    def encode(self):
        buf = BytesIO()
        buf.write(arm_angles._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">fff", self.base, self.shoulder, self.elbow))

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != arm_angles._get_packed_fingerprint():
            raise ValueError("Decode error")
        return arm_angles._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = arm_angles()
        self.base, self.shoulder, self.elbow = struct.unpack(">fff", buf.read(12))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if arm_angles in parents: return 0
        tmphash = (0x2e9f9239d6e338c7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if arm_angles._packed_fingerprint is None:
            arm_angles._packed_fingerprint = struct.pack(">Q", arm_angles._get_hash_recursive([]))
        return arm_angles._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", arm_angles._get_packed_fingerprint())[0]

